### ISSUE TITLE
OH prior years?

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#137] opened 2021-06-25 13:48 UTC
The Ohio scraper captures 2021 data from a [basic page](https://jfs.ohio.gov/warn/current.stm) with the current year's data. 

We should research whether it's possible to obtain prior year's via scraping. It not, we should file a records request for prior 5-10 years (or however far back we can go).

**Comment by palewire** [comment] 2022-01-20 00:16
This is a duplicate of #72

**Closed by palewire** 2022-01-20 00:16 UTC
Labels: enhancement, research, easy
